name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * 1'  # This will run every Monday at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: aroumeliotis/dotfiles  # Replace with the upstream repository details
          ref: main  # Replace with the default branch of the upstream repository

      - name: Check out the forked repository
        uses: actions/checkout@v2
        with:
          repository: <your-username>/<your-forked-repo>  # Replace with your forked repository details
          ref: main  # Replace with the default branch of your forked repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/mylinuxforwork/dotfiles.git  # Replace with the upstream repository URL
          git fetch upstream
          git merge upstream/main  # Replace 'main' with the default branch of the upstream repository
          git push origin main  # Replace 'main' with the default branch of your forked repository
