name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * 1'  # This will run every Monday at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: mylinuxforwork/dotfiles  # Upstream repository details
          ref: main  # Default branch of the upstream repository

      - name: Check out the forked repository
        uses: actions/checkout@v2
        with:
          repository: aroumeliotis/dotfiles  # Your forked repository details
          ref: main  # Default branch of your forked repository
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git user
        run: |
          git config --global user.email "aroumeliotis@gmail.com"  # Replace with your email
          git config --global user.name "Andreas"  # Replace with your name

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/mylinuxforwork/dotfiles.git  # Upstream repository URL
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories  # Default branch of the upstream repository
          git push origin main  # Default branch of your forked repository
